name: aframe-online-deployment
channels:
  - conda-forge
dependencies:
  # python/env dependencies
  - python=3.10
  - pip
  - poetry
  - jsonargparse
  - scipy=<1.15
  - h5py
  # general GW
  - healpy
  - gwpy=3.0.8
  - libgcc
  - ligo-gracedb
  # auth libs
  - krb5
  - ciecplib
  - requests-gssapi
  - htgettoken
  # frame file I/O dependencies
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  - python-ligo-lw
