name: aframe-online-deployment
channels:
  - conda-forge
dependencies:
  # python/env dependencies
  - python=3.9
  - pip
  - poetry
  - jsonargparse
  # need these for utils lib
  # TODO: add constraints for better pinning
  - bokeh
  - scipy
  - h5py
  # general GW/auth deps
  - healpy
  - gwpy=3.0.8
  - libgcc
  - ligo-gracedb
  # auth libs
  - krb5
  - ciecplib
  - requests-gssapi
  # frame file I/O dependencies
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  - python-ligo-lw
