[tool.poetry]
name = "aframe"
version = "0.0.1"
description = "End-to-end aframe pipeline components"
authors = [
    "Alec Gunny <alec.gunny@ligo.org>",
    "Ethan Marx <emarx@mit.edu>",
    "William Benoit"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
luigi = "^3.0"
utils = {path = "./libs/utils", develop = true} 
ml4gw-hermes = ">=0.2.0" 
law = ">=0.1.19"
kr8s = "^0.10.0"
pykube-ng = {version = "^23.6.0", extras = ["oidc"]}
spython = "^0.2"
boto3 = "^1.34.4"
numpy = "^1.26.4"
cloudpathlib = "^0.18.1"
psutil = "^5.9.8"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
jsonargparse = "^4.27.1"
conda-lock = "^2.5.1"
pre-commit = "^3.7.0"

[tool.poetry.group.docs.dependencies]
Sphinx = ">5.0"
sphinx-rtd-theme = "^2.0.0"
myst-parser = "^2.0.0"
sphinx-autodoc-typehints = "^2.0.0"
linkify-it-py = "^2.0.3"
sphinx-tabs = "^3.4.7"

[tool.poetry.scripts]
build-containers = "scripts.build_containers:main"
aframe-init = "scripts.aframe_init:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | _build
  | dist
  | docs
)/
'''


[tool.isort]
known_first_party = ["aframe", "train", "utils", "online", "data", "infer", "plots", "export", "ledger", "p_astro", "priors"]
known_third_party = ["amplfi"]
multi_line_output = 3
include_trailing_comma = true
