name: bbhnet-generate_glitches
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gwpy=2.1.0
  - astropy<5.0.0 
  - python-ldas-tools-framecpp
  - python-nds2-client
  - python-ligo-lw
  - pyomicron=1.1.0
  - omicron=2.4.2
