[tool.poetry]
name = "infer"
version = "0.0.1"
description = "Perform local IaaS inference with BBHNet"
authors = ["Alec Gunny <alec.gunny@gmail.com>"]
# readme = "README.md"

[tool.poetry.scripts]
infer = "infer.main:main"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
"bbhnet.io" = {path = "../../../libs/io", develop = true}
"bbhnet.parallelize" = {path = "../../../libs/parallelize", develop = true}
"bbhnet.logging" = {path = "../../../libs/logging", develop = true}

"hermes.stillwater" = {path = "../../../hermes/hermes/hermes.stillwater", develop = true}
"hermes.aeriel" = {path = "../../../hermes/hermes/hermes.aeriel", extras = ["serve"], develop = true}
typeo = {git = "https://github.com/ML4GW/typeo.git"}

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry>=1.2"]
build-backend = "poetry.masonry.api"
