[tool.poetry]
name = "infer"
version = "0.0.1"
description = "Perform local IaaS inference with BBHNet"
authors = ["Alec Gunny <alec.gunny@gmail.com>"]
# readme = "README.md"

[tool.poetry.scripts]
infer = "infer.main:main"
deploy-infer = "infer.deploy:main"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
ratelimiter = "^1.2"
psutil = "^5.0"

# other ml4gw utilities
typeo = {git = "https://github.com/ML4GW/typeo.git", branch = "main"}

# local bbhnet utilities
"bbhnet.analysis" = {path = "../../../libs/analysis", develop = true}
"bbhnet.deploy" = {path = "../../../libs/deploy", develop = true}
"bbhnet.io" = {path = "../../../libs/io", develop = true}
"bbhnet.logging" = {path = "../../../libs/logging", develop = true}

# hermes utilities
"hermes.aeriel" = {path = "../../../hermes/hermes/hermes.aeriel", develop = true}
"hermes.stillwater" = {path = "../../../hermes/hermes/hermes.stillwater", develop = true}

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
