name: bbhnet-datagen
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gwpy
  - astropy
  # frame file I/O dependencies
  - python-ldas-tools-framecpp
  - python-nds2-client
  # omicron dependencies
  - python-ligo-lw
  - pyomicron
  - omicron
  - dqsegdb2
  - uproot
  # injection dependencies
  - bilby<1.2
  - lalsuite
