apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:
  WANDB_API_KEY: {{ .Values.secret.wandbKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsKey }}
